export const TECH_LINKS: Record<string, string> = {
  "React": "https://react.dev",
  "TypeScript": "https://www.typescriptlang.org",
  "Tailwind CSS": "https://tailwindcss.com",
  "Bootstrap": "https://getbootstrap.com",
  "HTML5": "https://developer.mozilla.org/en-US/docs/Web/HTML",
  "CSS3": "https://developer.mozilla.org/en-US/docs/Web/CSS",
  "Node.js": "https://nodejs.org",
  "Express": "https://expressjs.com",
  "Django": "https://www.djangoproject.com",
  "DRF": "https://www.django-rest-framework.org",
  "Spring Boot": "https://spring.io/projects/spring-boot",
  "Flask": "https://flask.palletsprojects.com",
  "Scikit-learn": "https://scikit-learn.org",
  "XGBoost": "https://xgboost.readthedocs.io",
  "Pandas": "https://pandas.pydata.org",
  "NumPy": "https://numpy.org",
  "spaCy": "https://spacy.io",
  "Hugging Face": "https://huggingface.co",
  "YOLOv8": "https://docs.ultralytics.com",
  "U-Net": "https://arxiv.org/abs/1505.04597",
  "EfficientNet-B4": "https://arxiv.org/abs/1905.11946",
  "MediaPipe": "https://mediapipe.dev",
  "OpenCV": "https://opencv.org",
  "CNNs": "https://en.wikipedia.org/wiki/Convolutional_neural_network",
  "MySQL": "https://www.mysql.com",
  "PostgreSQL": "https://www.postgresql.org",
  "MongoDB": "https://www.mongodb.com",
  "SQLite": "https://www.sqlite.org",
  "Git": "https://git-scm.com",
  "Agile Scrum": "https://www.scrum.org",
  "SDLC": "https://en.wikipedia.org/wiki/Systems_development_life_cycle",
  "SPM": "https://en.wikipedia.org/wiki/Software_project_management",
  "SQE": "https://en.wikipedia.org/wiki/Software_quality_assurance",
  "Code Review": "https://en.wikipedia.org/wiki/Code_review",
  "Amazon SP API": "https://developer-docs.amazon.com/sp-api",
  "MERN": "https://www.mongodb.com/mern-stack",
  "Socket.io": "https://socket.io",
  "Stripe": "https://stripe.com",
};

export const NAV_LINKS = [
  { name: "About", href: "#about" },
  { name: "Skills", href: "#skills" },
  { name: "Portfolio", href: "#projects" },
  { name: "Journey", href: "#journey" },
  { name: "Reviews", href: "#reviews" },
  { name: "Contact", href: "#contact" },
];
